### ISSUE TITLE
After new versions of Pirate Wallet-Lite to date, 59.xxxxx tokens keep disappearing in each updated version to date

### ISSUE THREAD

**Issue by Tracex-sys** [PirateNetwork/PirateWallet-Lite#121] opened 2023-08-16 20:27 UTC
Support, this is not a new issue. The problem I am having is that 59.xxxxxx tokens keep disappearing along with error messages I don't
understand. I have sent numerous messages on this issue and still, no resolve. What is the issue that persists in this matter? 
Please advise, Charles Swank

![Screenshot_547](https://github.com/PirateNetwork/PirateWallet-Lite/assets/65625306/59eb9f7d-ba36-45dd-ac9e-5b302293f179)
SS#547 above displays repeated attempts to reach someone in the PirateWallet-Lite community knowledgeable to address problem.

![Screenshot_526](https://github.com/PirateNetwork/PirateWallet-Lite/assets/65625306/67706064-43e4-42e5-99fd-0a0bb0586e75)
SS#526 above displays (Version 1.0.8) 3 original purchases I made. Since that time, NO SEND OR RECEIVE TRANSACTIONS WERE EVER MADE SINCE. 

![Screenshot_535](https://github.com/PirateNetwork/PirateWallet-Lite/assets/65625306/5ea8f0e5-29bc-4cb8-814e-16d48353898c)
SS#535 above displays (Version 1.0.8) over 59.xxxxxxx tokens keep disappearing repeatedly.

![Screenshot_546](https://github.com/PirateNetwork/PirateWallet-Lite/assets/65625306/3336dc2c-6a1b-49e6-96a5-70825bfdde37)
SS#546 above displays (Version 1.0.9) recovered all tokens and now, over 59.xxxxx tokens have disappeared again and again just like Version 1.0.8.

![Screenshot_548](https://github.com/PirateNetwork/PirateWallet-Lite/assets/65625306/5c0bc1a2-8788-4b1e-afc1-a80351d95101)
SS#548 above displays (Version 1.0.9) "There was an error connecting to zcashd". This type of error repeatedly is displayed and among other errors as well. 59.xxxxxxxtokens disappeared again.

**Comment by TheComputerGenie** [comment] 2023-08-16 20:30
duplicate of https://github.com/PirateNetwork/PirateWallet-Lite/issues/115

**Closed by TheComputerGenie** 2023-08-16 20:30 UTC
