### ISSUE TITLE
WHEN WILL I RECOVER MY 59.XXXXXXX PIRATECHAIN TOKENS BACK? THEY KEEP DISAPPEARING

### ISSUE THREAD

**Issue by Tracex-sys** [PirateNetwork/PirateWallet-Lite#118] opened 2023-08-03 19:29 UTC
Support, I am still having RE OCCURING PROBLEMS, MY TOKENS KEEP DISAPPEARING CONTINUALLY, WHAT'S WRONG?
PLEASE REVIEW ATTACHMENTS BELOW. Thank you, Charles Swank  swankm727o522@protonmail.com

![Screenshot_548](https://github.com/PirateNetwork/PirateWallet-Lite/assets/65625306/373d59b4-96b8-4d42-8bd3-00195d1ac4f3)
![Screenshot_526](https://github.com/PirateNetwork/PirateWallet-Lite/assets/65625306/93129a5a-d1b8-4b4e-9c1e-fec94bd8f824)
![Screenshot_535](https://github.com/PirateNetwork/PirateWallet-Lite/assets/65625306/1eaed8d1-d238-4e52-b4e0-5aeaba36848b)
![Screenshot_547](https://github.com/PirateNetwork/PirateWallet-Lite/assets/65625306/df2d9aad-c4b7-4ebf-83b4-98710a5836d8)
![Screenshot_546](https://github.com/PirateNetwork/PirateWallet-Lite/assets/65625306/b98fe20f-aed0-4646-8f25-7696dc9c2aeb)

**Comment by TheComputerGenie** [comment] 2023-08-16 20:29
duplicate of https://github.com/PirateNetwork/PirateWallet-Lite/issues/115

**Closed by TheComputerGenie** 2023-08-16 20:29 UTC
Labels: bug
